apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: spring-boot-container
          image: 192.168.0.102:8083/380b8b
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: nexus-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
