apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-ui
  template:
    metadata:
      labels:
        app: game-ui
    spec:
      containers:
        - name: ui-container
          image: 192.168.0.102:8083/18f29a
          ports:
            - containerPort: 3006
      imagePullSecrets:
        - name: nexus-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: game-ui
spec:
  selector:
    app: game-ui
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
  type: LoadBalancer
